### PR TITLE
Add clipboard support for macOS and Linux in q function

### PR DESCRIPTION
**Pull request by the-mentor**
This PR adds basic MacOS and Linux support

### CODE REVIEW

**Comment by dfinke** [comment]
Sweet @the-mentor thanks for the PR. I am heading out for the next week - if I don't merge it by next week - please ping me again here.

**Comment by dfinke** [comment]
Please update if using `elseif`.
Is there a missing `}` after the `else`?

**Comment by the-mentor** [comment]
> Please update if using `elseif`. Is there a missing `}` after the `else`?

you are correct I accidentally mistyped.
I've fixed it now.

**Comment by the-mentor** [comment]
@dfinke I ended up simplifying the code and using the `Set-Clipboard` command that is cross platform.
I tested it on ubuntu, macos and windows 
i also tested on windows powershell 5
all of them seem to work

**Comment by dfinke** [comment]
Thanks for checking that, was wondering if `set-clipboard` would work across all.

**Comment by the-mentor** [comment]
@dfinke ping 🏓

**Comment by dfinke** [comment]
@the-mentor Thanks for the heads up and PR! Published!

**Pull request merged**
